
spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
#    url: jdbc:h2:~/spring-boot-h2-db2;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
  h2:
    console:
      enabled: true



